import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Travel Log App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <div className='flex justify-center items-center my-4 font-bold text-3xl'>
          Travel Log
        </div>
        <div className='flex justify-center items-center my-4 font-bold text-3xl'>
          MERN Project
        </div>
        <div className='flex justify-center items-center my-4 font-bold text-3xl'>
          18CSE302J
        </div>
        <div className='font-bold text-xl underline'>Team Members</div>
        <ul className='pl-10 list-disc text-lg'>
          <li>Shivam Shekhar (RA1911030010026)</li>
          <li>Harishankar (RA19110300....)</li>
          <li>Pratul Anand (RA19110300....)</li>
        </ul>
        <div className='flex justify-center'>
          <Link href='/travel-log' passHref>
            <button className='bg-black rounded-lg text-white px-4 p-2 font-medium text-xl'>
              Add a Log
            </button>
          </Link>
        </div>
      </div>

      {/* <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
