import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Travel Log App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="flex justify-center items-center my-4 font-bold text-3xl">
          Travel Log App
        </div>
        <div className="flex justify-center items-center my-4 font-bold text-3xl">
          MERN Project
        </div>
        <div className="flex justify-center items-center my-4 font-bold text-3xl">
          18CSE302J
        </div>
        <div className="font-bold text-xl underline">Team Members</div>
        <ul className="pl-10 list-disc text-lg">
          <li>Shivam Shekhar (RA1911030010026)</li>
          <li>Harishankar (RA1911027010022)</li>
          <li>Pratul Anand (RA1911027010032)</li>
        </ul>
        <div className="flex justify-center">
          <Link href="/auth" passHref>
            <button className="bg-black rounded-lg text-white px-4 p-2 font-medium text-xl">
              Login
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
